# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Topics
    url: tags/
    weight: 20
  - name: Uses
    url: uses/
    weight: 30
  - name: Tags
    identifier: tags
    weight: 40
  - name: C/C++
    parent: tags
    url: tags/cpp
    weight: 10
