# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 1000
  - name: Tags
    url: tags/
    identifier: tags
    weight: 100
  - name: child
    parent: tags
    identifier: child
    weight: 10
  - name: grandson
    parent: child
    weight: 1