# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Categories
    url: blog/categories/
    weight: 20
  - name: Tags
    url: tags/
    weight: 30